### ISSUE TITLE
Error when running testset_resolver

### ISSUE THREAD

**Issue by jalagar** [OpenRarity/open-rarity#79]
**Describe the bug**
I ran `python3 -m open_rarity.resolver.testset_resolver external` to try to get a test example working (not using caching) for `cool-cats-nft`. See output log below.

**Information**

* Collection link/name - cool-cats-nft
* Contract standard - Not sure
* Chain - ETH

**To Reproduce**
`python3 -m open_rarity.resolver.testset_resolver external`

**Expected behavior**
It should output the rarity for cool-cats-nft

**Screenshots**
```
Executing main: with Namespace(resolve_external_rarity='external', cache_fetched_data=True, filename='test_collections.json')
Fetching collection and token trait data for: cool-cats-nft
Fetching external rarity ranks for: cool-cats-nft
Starting batch 0 for collection cool-cats-nft: Processing 293 tokens
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jamesuejio/Crypto/open-rarity/open_rarity/resolver/testset_resolver.py", line 568, in <module>
    resolve_collection_data(
  File "/Users/jamesuejio/Crypto/open-rarity/open_rarity/resolver/testset_resolver.py", line 226, in resolve_collection_data
    tokens_with_rarity: list[TokenWithRarityData] = get_tokens_with_rarity(
  File "/Users/jamesuejio/Crypto/open-rarity/open_rarity/resolver/testset_resolver.py", line 151, in get_tokens_with_rarity
    external_rarity_provider.fetch_and_update_ranks(
  File "/Users/jamesuejio/Crypto/open-rarity/open_rarity/resolver/rarity_providers/external_rarity_provider.py", line 483, in fetch_and_update_ranks
    self._add_rarity_sniffer_rarity_data(
  File "/Users/jamesuejio/Crypto/open-rarity/open_rarity/resolver/rarity_providers/external_rarity_provider.py", line 364, in _add_rarity_sniffer_rarity_data
    token_ids_to_ranks = fetch_rarity_sniffer_rank_for_collection(
  File "/Users/jamesuejio/Crypto/open-rarity/open_rarity/resolver/rarity_providers/external_rarity_provider.py", line 123, in fetch_rarity_sniffer_rank_for_collection
    tokens_to_ranks: dict[int, int] = {
  File "/Users/jamesuejio/Crypto/open-rarity/open_rarity/resolver/rarity_providers/external_rarity_provider.py", line 124, in <dictcomp>
    str(nft["id"]): int(nft["positionId"]) for nft in response.json()["data"]
TypeError: string indices must be integers
```

**Environment**
 - OS: [e.g. iOS] - MacOS Monterey 12.2.1
 - Python [e.g. 3.10.3] - 3.10.7
 - Library Version [e.g. 1.0] - Latest master

**Additional context**
I was just trying to play around and get a test example working (not using caching).

**Comment by vickygos** [comment]
@jalagar I just re-rank the command from latest master and could not hit error mentioned. Could you retry it after pulling latest and see if you still have an issue? One theory could be that at that moment data was not returned.

**Comment by jalagar** [comment]
Closing as resolved
